# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.

version: 2.1

executors:
    rsync_box:
        parameters:
            image:
                type: string
                default: aplazame/alpine:0.1.7-rsync
            working_directory:
                type: string
                default: /tmp/workspace
        docker:
        - image: << parameters.image >>
        working_directory: << parameters.working_directory >>

commands:
    folder:
        description: "A simple encapsulation of doing a rsync"
        parameters:
            src:
                type: string
            user:
                type: string
            host:
                type: string
            dest:
                type: string
            overwrite:
                type: boolean
                default: true
            arguments:
                type: string
                default: ''
        steps:
        - run:
            name: Gathering the public SSH
            command: ssh-keyscan << parameters.host >> >> ~/.ssh/known_hosts

        - run:
            name: RSync Deploy
            command: >
                rsync -rva<<# parameters.overwrite >> --delete<</ parameters.overwrite >> \
                    << parameters.src >>/ \
                    << parameters.user >>@<< parameters.host >>:<< parameters.dest >>\
                    <<# parameters.arguments >> << parameters.arguments >><</ parameters.arguments >>;

jobs:
    deploy:
        executor: << parameters.executor >>
        parameters:
            workspace:
                description: working directory
                type: string
                default: /tmp/workspace

            executor:
                description: executor for s3_deploy
                type: executor
                default: rsync_box

            do_deploy:
                description: commands executed after rsync setup
                type: steps
                default: []
        steps:
        - attach_workspace:
            at: << parameters.workspace >>

        - add_ssh_keys

        - steps: << parameters.do_deploy >>
