# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.

version: 2.1

executors:
    s3_box:
        parameters:
            image:
                type: string
                default: aplazame/alpine:0.1.7-aws
            working_directory:
                type: string
                default: /tmp/workspace
        docker:
        - image: << parameters.image >>
        working_directory: << parameters.working_directory >>

commands:
    folder:
        description: "Parametrized folder deploy to S3"
        parameters:
            bucket_name:
                type: string
            src:
                type: string
            dest:
                type: string
            acl:
                type: string
                default: private
            overwrite:
                type: boolean
                default: true
            arguments:
                type: string
                default: ''
        steps:
            - run:
                name: "Deploying folder to s3: << parameters.src >> > s3:<< parameters.bucket_name >>/<< parameters.dest >>"
                command: |
                    aws s3 sync --acl << parameters.acl >> \
                        --cache-control "private, max-age:3600" \
                        <<# parameters.overwrite >>--delete <</ parameters.overwrite >>\
                        "<< parameters.src >>" "s3://<< parameters.bucket_name >>/<< parameters.dest >>"\
                        <<# parameters.arguments >> << parameters.arguments >><</ parameters.arguments >>;

    file:
        description: "Parametrized single file deploy to S3"
        parameters:
            bucket_name:
                type: string
            src:
                type: string
            dest:
                type: string
                default: ""
            acl:
                type: string
                default: private
            content_type:
                type: string
            cache_control:
                type: string
                default: private, max-age:3600
            arguments:
                type: string
                default: ''
        steps:
            - run:
                name: "Deploying file to s3: << parameters.src >> > s3:<< parameters.bucket_name >>/<< parameters.dest >>"
                command: >
                    aws s3 cp --acl << parameters.acl >> "<< parameters.src >>" "s3://<< parameters.bucket_name >>/<< parameters.dest >>" \
                        --cache-control "<< parameters.cache_control >>" \
                        --content-type "<< parameters.content_type >>"\
                        <<# parameters.arguments >> << parameters.arguments >><</ parameters.arguments >>;

jobs:
    deploy:
        executor: << parameters.executor >>
        parameters:
            executor:
                description: executor for s3_deploy
                type: executor
                default: s3_box

            do_deploy:
                description: commands to be executed after for S3 deploy
                type: steps
                default: []
        steps:
        - attach_workspace:
            at: /tmp/workspace

        - steps: << parameters.do_deploy >>